name: Create Accountability Issue - {name}

on:
  schedule:
    # Runs at 8:20 AM UTC every 
    - cron: '20 8 * * {day_of_week}'
  workflow_dispatch:
    # Allows manual trigger



permissions:
  issues: write
  contents: read

jobs:
  create-issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      
      - name: Install labtools
        run: |
          pip install git+http://github.com/ml4sts/labtools.git

      - name: Get existing issues
        id: get-issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh search issues --owner=ml4sts --assignee {username} --json url  --state=open \
          -- -label:goals,log > open_issues.json
          dates=$(lab acc dates)
          gh search issues --owner=ml4sts --assignee {username} --json url  --updated "$dates" \
          --state=closed -- -label:goals,log > closed_issues.json
          
          
      - name: Format content and create issue
        id: create-issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          lab acc create  > issue_template.md
                 
          gh issue create --title "{name} $(date +"%Y-%m-%d")" --body-file issue_template.md --label "log" --assignee brownsarahm