# TEMPLATE NOTE: this file will be written without further modification and
# TEMPLATE NOTE: must be valid yaml (only these notes will be removed)
name: Schedule Accountability Issues

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name as you want it to appear in the issue"
        required: true
        type: string
      day_of_week:
        description: "Enter the day of the week (0 for Sunday, 6 for Saturday)"
        required: true
        type: choice
        options:
          - "0"
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  schedule-acountability:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_EDITING_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install labtools
        run: |
          pip install git+http://github.com/ml4sts/labtools.git

      - name: Run lab accountability schedule command
        run: |
          lab acc schedule --name "${{ github.event.inputs.name }}" \
            --day-of-week "${{ github.event.inputs.day_of_week }}" \
            --username "${{ github.actor }}"


      - name: Create a pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: schedule-acc-${{ github.event.inputs.name }}
          title: "(Re)schedule Accountability Checkins for ${{ github.event.inputs.name }}"
          body: |
            creates or updates the scheduled acountability for ${{ github.event.inputs.name }}

            PR is for review, but if not debugging labtools, it can be merged by anyone
          commit-message: "(re)schedule Acc for ${{ github.event.inputs.name }}"
          assignees: ${{ github.actor }},brownsarahm
          token: ${{ secrets.WORKFLOW_EDITING_TOKEN }}

          